(ns project-euler.exercise2
  (:require [clojure.string :as string]))


(comment
  Each new term in the Fibonacci sequence is generated by adding
  the previous two terms. By starting with 1 and 2, the first
  10 terms will be

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do
  not exceed four million, find the sum of the even-valued terms.)

(defn fibonacci-generator
  "generates a vector of fibonacci sequence given max number"
  [num-limit]
  (loop [fiblist [1 1] num1 1 num2 1]
    (if (< (last fiblist) num-limit)
     (recur (conj fiblist (+ num1 num2)) num2 (+ num1 num2))
     (reduce + (filter even? fiblist)))))

